### ISSUE TITLE
Understanding display

### ISSUE THREAD

**Issue by bbarker** [ajnsit/concur-documentation#10]
For `display` I'm having trouble understanding why the widget argument has a value type that is a Signal itself:

```purescript
display :: forall v. Widget v (Signal v Unit) -> Signal v Unit
```

Intuitively I would think it would be:

```purescript
display :: forall v. Widget v Unit -> Signal v Unit
```

But then this is basically `hold`. So another point of confusion is when we need `hold` vs `display`. The doc readme says "simple display widget", which makes me wonder if a "display widget" is something different from a normal widget.

Thanks!

**Comment by ajnsit** [comment]
These functions are slightly badly named. I should rename `display` to `stepUnit` and add a new `holdUnit` which has the type signature that you want. Basically these are convenience functions that provide the initial value for `hold` and `step` when its type has only one possible inhabitant (i.e. `Unit`).

The "display widget" that the docs refer to are widgets of the type `forall a. Widget HTML a` i.e. things that never end. Such widgets are typically used to display static things like text. Because of their polymorphic return type, they can be passed to `display` without issues (the polymorphic `a` is just resolved to a `Signal ...` by the type checker).

**Comment by ajnsit** [comment]
I'm not happy with the names `holdUnit` etc. either, so I'm going to hold off on renaming the functions. Meanwhile I have added some more exposition on "display widgets" to the docs.

Thanks for taking the time to go through the documentation. It's really helpful to see what problems a person not initially familiar with Concur would encounter!

Closing this, feel free to reopen.
